// lib/recipes-data.ts

export interface RecipeData {
  id: number
  title: string
  image: string
  readyInMinutes: number
  servings: number
  summary: string
  instructions: string
  ingredients: string[]
  cuisines: string[]
  diets: string[]
  dishTypes: string[]
  spoonacularScore: number
  nutrition?: {
    calories?: number
    protein?: string
    carbs?: string
    fat?: string
  }
}

export const ALL_CURATED_RECIPES: RecipeData[] = [
  // ==========================================
  // BREAKFAST DISHES (20+ Dishes)
  // ==========================================
  {
    id: 101,
    title: "Fluffy Golden Buttermilk Pancakes",
    image: "https://images.unsplash.com/photo-1528207776546-365bb710ee93?auto=format&fit=crop&w=800&q=80",
    readyInMinutes: 20,
    servings: 4,
    summary: "Extra soft, thick, and fluffy buttermilk pancakes served with warm maple syrup, melting butter, and fresh berries.",
    instructions: "1. In a large bowl, whisk flour, sugar, baking powder, baking soda, and salt.\n2. In a separate bowl, whisk buttermilk, melted butter, and eggs until smooth.\n3. Gently fold wet ingredients into dry ingredients until just combined.\n4. Heat a non-stick griddle over medium heat and lightly butter it.\n5. Pour 1/4 cup batter for each pancake. Cook until bubbles form on top, flip, and cook until golden.\n6. Serve hot with maple syrup and blueberries.",
    ingredients: ["2 cups All-Purpose Flour", "2 tbsp Granulated Sugar", "2 tsp Baking Powder", "1/2 tsp Baking Soda", "1.5 cups Buttermilk", "2 Large Eggs", "3 tbsp Melted Butter", "Fresh Blueberries & Maple Syrup"],
    cuisines: ["American"],
    diets: ["Vegetarian"],
    dishTypes: ["breakfast"],
    spoonacularScore: 94,
    nutrition: { calories: 350, protein: "8g", carbs: "52g", fat: "12g" }
  },
  {
    id: 102,
    title: "Classic Shakshuka with Poached Eggs & Feta",
    image: "https://images.unsplash.com/photo-1590412200988-a436970781fa?auto=format&fit=crop&w=800&q=80",
    readyInMinutes: 25,
    servings: 3,
    summary: "Spiced North African & Middle Eastern dish of gently poached eggs in a rich, simmering tomato, bell pepper, and cumin sauce.",
    instructions: "1. Sauté onions and bell peppers in olive oil until tender.\n2. Add garlic, cumin, paprika, and cayenne pepper.\n3. Pour in crushed tomatoes and simmer for 10 minutes.\n4. Crack eggs into sauce wells, cover and simmer for 6 minutes until whites set.\n5. Garnish with crumbled feta and fresh cilantro. Serve with crusty bread.",
    ingredients: ["4 Large Eggs", "1 can Crushed Tomatoes", "1 Bell Pepper", "1 Onion", "3 cloves Garlic", "1 tsp Cumin & Paprika", "1/4 cup Crumbled Feta", "Fresh Cilantro"],
    cuisines: ["Middle Eastern", "Mediterranean"],
    diets: ["Vegetarian", "Healthy", "Gluten Free"],
    dishTypes: ["breakfast", "brunch"],
    spoonacularScore: 96,
    nutrition: { calories: 290, protein: "14g", carbs: "22g", fat: "15g" }
  },
  {
    id: 103,
    title: "Avocado Toast with Poached Egg & Microgreens",
    image: "https://images.unsplash.com/photo-1525351484163-7529414344d8?auto=format&fit=crop&w=800&q=80",
    readyInMinutes: 15,
    servings: 2,
    summary: "Artisan sourdough topped with creamy seasoned avocado mash, perfectly poached organic eggs, chili flakes, and crisp microgreens.",
    instructions: "1. Toast sourdough slices until crisp.\n2. Mash avocados with lemon juice, sea salt, pepper, and olive oil.\n3. Poach eggs in simmering water for 3 minutes.\n4. Spread avocado on toast, top with poached eggs, chili flakes, and microgreens.",
    ingredients: ["2 Slices Sourdough", "2 Ripe Avocados", "2 Eggs", "1 tbsp Lemon Juice", "Chili Flakes", "Everything Bagel Seasoning", "Microgreens"],
    cuisines: ["American"],
    diets: ["Vegetarian", "Healthy"],
    dishTypes: ["breakfast", "brunch"],
    spoonacularScore: 93,
    nutrition: { calories: 340, protein: "12g", carbs: "28g", fat: "20g" }
  },
  {
    id: 104,
    title: "Classic Eggs Benedict with Velvety Hollandaise",
    image: "https://images.unsplash.com/photo-1608039829572-78524f79c4c7?auto=format&fit=crop&w=800&q=80",
    readyInMinutes: 30,
    servings: 2,
    summary: "Toasted English muffins topped with seared Canadian bacon, poached eggs, and freshly whisked rich lemon-butter Hollandaise sauce.",
    instructions: "1. Whisk egg yolks, lemon juice, and warm butter over gentle heat for hollandaise.\n2. Sear Canadian bacon slices until golden.\n3. Poach eggs in simmering water for 3 minutes.\n4. Layer toasted muffins with bacon, eggs, and warm hollandaise sauce.",
    ingredients: ["2 English Muffins", "4 Eggs", "4 slices Canadian Bacon", "3 Egg Yolks", "1/2 cup Clarified Butter", "1 tbsp Lemon Juice", "Chives"],
    cuisines: ["French", "American"],
    diets: ["High Protein"],
    dishTypes: ["breakfast", "brunch"],
    spoonacularScore: 91,
    nutrition: { calories: 480, protein: "22g", carbs: "26g", fat: "32g" }
  },
  {
    id: 105,
    title: "Belgian Sugar Waffles with Fresh Berries",
    image: "https://images.unsplash.com/photo-1562376552-0d160a2f238d?auto=format&fit=crop&w=800&q=80",
    readyInMinutes: 25,
    servings: 4,
    summary: "Crisp on the outside, tender on the inside authentic Belgian waffles served with whipped cream and a medley of fresh strawberries and raspberries.",
    instructions: "1. Whisk dry ingredients in one bowl and wet ingredients in another.\n2. Fold stiffly beaten egg whites into batter.\n3. Cook in a preheated Belgian waffle iron until deep golden.\n4. Top with whipped cream and fresh berries.",
    ingredients: ["2 cups Flour", "2 tbsp Sugar", "2 Eggs (separated)", "1.75 cups Milk", "1/2 cup Melted Butter", "Fresh Berries", "Whipped Cream"],
    cuisines: ["European", "Belgian"],
    diets: ["Vegetarian"],
    dishTypes: ["breakfast"],
    spoonacularScore: 90,
    nutrition: { calories: 410, protein: "9g", carbs: "48g", fat: "19g" }
  },
  {
    id: 106,
    title: "French Brioche Toast with Cinnamon & Vanilla",
    image: "https://images.unsplash.com/photo-1484723091739-0045e483568c?auto=format&fit=crop&w=800&q=80",
    readyInMinutes: 20,
    servings: 4,
    summary: "Thick slices of buttery brioche soaked in a rich custard infused with pure vanilla, Ceylon cinnamon, and a hint of nutmeg.",
    instructions: "1. Whisk eggs, milk, cream, vanilla, and cinnamon.\n2. Dip brioche slices for 20 seconds per side.\n3. Fry in butter over medium heat for 3 minutes per side until caramelized.\n4. Serve with maple syrup and powdered sugar.",
    ingredients: ["8 thick Brioche slices", "4 Eggs", "3/4 cup Milk", "1/4 cup Cream", "1 tsp Vanilla", "1 tsp Cinnamon", "Butter", "Maple Syrup"],
    cuisines: ["French"],
    diets: ["Vegetarian"],
    dishTypes: ["breakfast"],
    spoonacularScore: 92,
    nutrition: { calories: 380, protein: "10g", carbs: "44g", fat: "18g" }
  },
  {
    id: 107,
    title: "Tropical Acai Superfood Power Bowl",
    image: "https://images.unsplash.com/photo-1590080875515-8a3a8dc5735e?auto=format&fit=crop&w=800&q=80",
    readyInMinutes: 10,
    servings: 2,
    summary: "Thick organic acai puree blended with frozen bananas and berries, topped with crunchy granola, chia seeds, coconut flakes, and kiwi.",
    instructions: "1. Blend frozen acai, banana, berries, and almond milk until thick.\n2. Spoon into bowls.\n3. Arrange sliced kiwi, strawberries, chia seeds, coconut, and granola on top.",
    ingredients: ["2 Acai Packets", "2 Bananas", "1/2 cup Almond Milk", "Granola", "Chia Seeds", "Coconut Flakes", "Fresh Kiwi & Berries"],
    cuisines: ["Healthy", "Brazilian"],
    diets: ["Vegan", "Vegetarian", "Healthy", "Gluten Free"],
    dishTypes: ["breakfast", "healthy"],
    spoonacularScore: 97,
    nutrition: { calories: 280, protein: "6g", carbs: "54g", fat: "6g" }
  },
  {
    id: 108,
    title: "Southwestern Breakfast Burrito with Chorizo",
    image: "https://images.unsplash.com/photo-1626700051175-6818013e1d4f?auto=format&fit=crop&w=800&q=80",
    readyInMinutes: 25,
    servings: 4,
    summary: "Warm flour tortillas packed with fluffy scrambled eggs, spiced chorizo, crispy potatoes, black beans, cheddar, and homemade pico de gallo.",
    instructions: "1. Cook and crumble chorizo.\n2. Scramble eggs softly.\n3. Fill tortillas with eggs, chorizo, beans, potatoes, cheese, and salsa.\n4. Roll and sear on a skillet until crispy.",
    ingredients: ["4 Tortillas", "6 Eggs", "1/2 lb Chorizo", "1 cup Cheddar Cheese", "1/2 cup Black Beans", "Hashbrowns", "Pico de Gallo"],
    cuisines: ["Mexican"],
    diets: ["High Protein"],
    dishTypes: ["breakfast"],
    spoonacularScore: 92,
    nutrition: { calories: 520, protein: "26g", carbs: "38g", fat: "29g" }
  },
  {
    id: 109,
    title: "Smoked Salmon & Cream Cheese Artisan Bagel",
    image: "https://images.unsplash.com/photo-1510693206972-df098062cb71?auto=format&fit=crop&w=800&q=80",
    readyInMinutes: 10,
    servings: 2,
    summary: "Freshly toasted New York style everything bagel smothered with herb cream cheese, premium cold-smoked Atlantic salmon, capers, and red onion.",
    instructions: "1. Toast bagels golden.\n2. Spread cream cheese generously on both sides.\n3. Layer smoked salmon, red onion, capers, fresh dill, and a squeeze of lemon.",
    ingredients: ["2 Everything Bagels", "6 oz Smoked Salmon", "4 tbsp Cream Cheese", "Capers", "Red Onion", "Fresh Dill", "Lemon"],
    cuisines: ["American"],
    diets: ["High Protein"],
    dishTypes: ["breakfast"],
    spoonacularScore: 95,
    nutrition: { calories: 430, protein: "24g", carbs: "46g", fat: "16g" }
  },
  {
    id: 110,
    title: "French Rolled Herb & Gruyère Omelette",
    image: "https://images.unsplash.com/photo-1510693206972-df098062cb71?auto=format&fit=crop&w=800&q=80",
    readyInMinutes: 12,
    servings: 2,
    summary: "Tender, silky classic French omelette rolled with nutty Gruyère cheese, chives, tarragon, and fresh parsley.",
    instructions: "1. Whisk eggs vigorously.\n2. Cook in foaming butter over medium-low heat while stirring rapidly.\n3. Add shredded Gruyère and herbs when soft-set.\n4. Roll gently and turn onto plate seam-side down.",
    ingredients: ["3 Eggs", "2 tbsp Butter", "1/4 cup Gruyère Cheese", "Fresh Chives & Tarragon", "Salt & White Pepper"],
    cuisines: ["French"],
    diets: ["Vegetarian", "High Protein", "Keto"],
    dishTypes: ["breakfast"],
    spoonacularScore: 93,
    nutrition: { calories: 310, protein: "19g", carbs: "2g", fat: "25g" }
  },
  {
    id: 111,
    title: "Vanilla Almond Overnight Oats with Chia & Berries",
    image: "https://images.unsplash.com/photo-1517673132405-a56a62b18caf?auto=format&fit=crop&w=800&q=80",
    readyInMinutes: 10,
    servings: 2,
    summary: "Hearty rolled oats steeped overnight with almond milk, chia seeds, Greek yogurt, pure vanilla, and topped with fresh raspberries and sliced almonds.",
    instructions: "1. Combine oats, chia seeds, yogurt, almond milk, maple syrup, and vanilla in jars.\n2. Refrigerate overnight.\n3. Top with fresh raspberries and toasted sliced almonds before serving.",
    ingredients: ["1 cup Rolled Oats", "1 cup Almond Milk", "1/2 cup Greek Yogurt", "1 tbsp Chia Seeds", "1 tbsp Maple Syrup", "Fresh Raspberries & Almonds"],
    cuisines: ["Healthy"],
    diets: ["Vegetarian", "Healthy"],
    dishTypes: ["breakfast", "healthy"],
    spoonacularScore: 95,
    nutrition: { calories: 260, protein: "11g", carbs: "42g", fat: "6g" }
  },
  {
    id: 112,
    title: "Huevos Rancheros with Warm Corn Tortillas",
    image: "https://images.unsplash.com/photo-1565299585323-38d6b0865b47?auto=format&fit=crop&w=800&q=80",
    readyInMinutes: 20,
    servings: 2,
    summary: "Crispy lightly fried corn tortillas topped with warm refried black beans, sunny-side up eggs, charred salsa ranchera, avocado, and cotija cheese.",
    instructions: "1. Warm and crisp tortillas in oil.\n2. Spread warm refried beans.\n3. Top with sunny-side up fried eggs and warm ranchero salsa.\n4. Garnish with avocado slices, cotija cheese, and cilantro.",
    ingredients: ["4 Corn Tortillas", "4 Eggs", "1 cup Refried Beans", "1 cup Ranchero Salsa", "1/4 cup Cotija Cheese", "1 Avocado", "Cilantro"],
    cuisines: ["Mexican"],
    diets: ["Vegetarian", "Gluten Free"],
    dishTypes: ["breakfast"],
    spoonacularScore: 94,
    nutrition: { calories: 380, protein: "16g", carbs: "36g", fat: "19g" }
  },
  {
    id: 113,
    title: "Spinach, Mushroom & Swiss Breakfast Frittata",
    image: "https://images.unsplash.com/photo-1525351484163-7529414344d8?auto=format&fit=crop&w=800&q=80",
    readyInMinutes: 30,
    servings: 6,
    summary: "Fluffy baked Italian egg frittata studded with sautéed cremini mushrooms, baby spinach, caramelized onions, and melted Swiss cheese.",
    instructions: "1. Sauté mushrooms, onions, and spinach in an oven-safe skillet.\n2. Whisk 8 eggs with milk, salt, and pepper.\n3. Pour eggs over vegetables and sprinkle Swiss cheese.\n4. Bake at 375°F for 18 minutes until golden and puffed.",
    ingredients: ["8 Eggs", "1/4 cup Milk", "1 cup Sliced Mushrooms", "2 cups Baby Spinach", "1 cup Swiss Cheese", "1 Onion", "Olive Oil"],
    cuisines: ["Italian"],
    diets: ["Vegetarian", "Gluten Free", "High Protein", "Keto"],
    dishTypes: ["breakfast", "brunch"],
    spoonacularScore: 92,
    nutrition: { calories: 250, protein: "16g", carbs: "5g", fat: "18g" }
  },
  {
    id: 114,
    title: "Crispy Belgian Blueberry Liège Waffles",
    image: "https://images.unsplash.com/photo-1562376552-0d160a2f238d?auto=format&fit=crop&w=800&q=80",
    readyInMinutes: 35,
    servings: 4,
    summary: "Rich yeast-leavened waffle dough studded with caramelized Belgian pearl sugar and served with a warm wild blueberry compote.",
    instructions: "1. Prepare yeast brioche batter and let rise.\n2. Fold in pearl sugar.\n3. Cook in hot waffle iron until sugar caramelizes on the crust.\n4. Top with warm blueberry compote.",
    ingredients: ["2 cups Flour", "1 packet Yeast", "1/2 cup Milk", "1/2 cup Butter", "1/2 cup Pearl Sugar", "1 cup Fresh Blueberries", "2 Eggs"],
    cuisines: ["Belgian"],
    diets: ["Vegetarian"],
    dishTypes: ["breakfast"],
    spoonacularScore: 93,
    nutrition: { calories: 430, protein: "7g", carbs: "58g", fat: "19g" }
  },
  {
    id: 115,
    title: "Mediterranean Breakfast Mezze Board",
    image: "https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&w=800&q=80",
    readyInMinutes: 15,
    servings: 2,
    summary: "A vibrant morning spread of soft boiled eggs, Kalamata olives, creamy hummus, labneh with za'atar, cucumber ribbons, and warm pita bread.",
    instructions: "1. Boil eggs for 6.5 minutes for jammy yolks.\n2. Arrange labneh drizzled with olive oil and za'atar on a platter.\n3. Add warm pita, cucumber, cherry tomatoes, olives, and soft-boiled eggs.",
    ingredients: ["4 Eggs", "1/2 cup Labneh or Greek Yogurt", "1 tsp Za'atar", "1 cup Cucumbers & Tomatoes", "1/2 cup Kalamata Olives", "Warm Pita Bread"],
    cuisines: ["Mediterranean", "Middle Eastern"],
    diets: ["Vegetarian", "Healthy"],
    dishTypes: ["breakfast"],
    spoonacularScore: 95,
    nutrition: { calories: 360, protein: "18g", carbs: "32g", fat: "18g" }
  },

  // ==========================================
  // LUNCH DISHES (20+ Dishes)
  // ==========================================
  {
    id: 121,
    title: "Classic Grilled Chicken Caesar Salad",
    image: "https://images.unsplash.com/photo-1550304943-4f24f54ddde9?auto=format&fit=crop&w=800&q=80",
    readyInMinutes: 25,
    servings: 2,
    summary: "Crisp Romaine hearts tossed in creamy homemade garlic-parmesan Caesar dressing, crowned with juicy sliced grilled chicken breast and golden herb croutons.",
    instructions: "1. Season and grill chicken breasts for 6 mins per side. Slice.\n2. Toss crisp chopped romaine with Caesar dressing and parmesan.\n3. Top with warm sliced chicken, garlic croutons, and cracked pepper.",
    ingredients: ["2 Chicken Breasts", "1 Head Romaine", "1/2 cup Shaved Parmesan", "1 cup Garlic Croutons", "3 tbsp Caesar Dressing", "Lemon"],
    cuisines: ["Italian", "American"],
    diets: ["High Protein"],
    dishTypes: ["lunch", "salad"],
    spoonacularScore: 95,
    nutrition: { calories: 420, protein: "38g", carbs: "14g", fat: "22g" }
  },
  {
    id: 122,
    title: "Italian Caprese Panini on Focaccia",
    image: "https://images.unsplash.com/photo-1528735602780-2552fd46c7af?auto=format&fit=crop&w=800&q=80",
    readyInMinutes: 15,
    servings: 2,
    summary: "Toasted rosemary focaccia sandwich layered with fresh buffalo mozzarella, ripe heirloom tomatoes, aromatic basil pesto, and aged balsamic glaze.",
    instructions: "1. Slice focaccia and spread pesto on both sides.\n2. Layer mozzarella, heirloom tomatoes, and basil leaves.\n3. Drizzle with balsamic glaze and grill until cheese melts.",
    ingredients: ["2 Focaccia Rolls", "8 oz Buffalo Mozzarella", "2 Heirloom Tomatoes", "3 tbsp Pesto", "Fresh Basil", "Balsamic Glaze"],
    cuisines: ["Italian"],
    diets: ["Vegetarian"],
    dishTypes: ["lunch", "sandwich"],
    spoonacularScore: 92,
    nutrition: { calories: 460, protein: "18g", carbs: "42g", fat: "24g" }
  },
  {
    id: 123,
    title: "Crispy Falafel & Tahini Mezze Wrap",
    image: "https://images.unsplash.com/photo-1593001874117-c99c800e3eb7?auto=format&fit=crop&w=800&q=80",
    readyInMinutes: 25,
    servings: 4,
    summary: "Warm flatbread filled with golden herb falafels, crisp cucumber-tomato salad, creamy hummus, pickled red cabbage, and nutty garlic tahini sauce.",
    instructions: "1. Fry falafel patties until crispy.\n2. Spread hummus inside warm flatbreads.\n3. Add falafels, diced cucumber, tomatoes, and drizzle with tahini sauce.",
    ingredients: ["1 can Chickpeas", "Fresh Parsley & Cilantro", "4 Flatbreads", "1/2 cup Hummus", "Tahini Sauce", "Pickled Cabbage & Tomatoes"],
    cuisines: ["Middle Eastern"],
    diets: ["Vegan", "Vegetarian", "Healthy"],
    dishTypes: ["lunch", "wrap"],
    spoonacularScore: 94,
    nutrition: { calories: 390, protein: "14g", carbs: "52g", fat: "15g" }
  },
  {
    id: 124,
    title: "Ahi Tuna & Avocado Hawaiian Poke Bowl",
    image: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=800&q=80",
    readyInMinutes: 20,
    servings: 2,
    summary: "Fresh sashimi-grade ahi tuna cubes marinated in sesame-soy sauce, served over seasoned sushi rice with edamame, seaweed salad, mango, and spicy mayo.",
    instructions: "1. Marinate diced tuna in soy sauce, sesame oil, and scallions.\n2. Scoop seasoned sushi rice into bowls.\n3. Top with tuna, avocado, mango, edamame, and spicy sriracha mayo.",
    ingredients: ["10 oz Sushi Tuna", "2 cups Sushi Rice", "1 Avocado", "1/2 cup Edamame", "1/2 cup Mango", "Soy Sauce & Sesame Oil", "Spicy Mayo"],
    cuisines: ["Hawaiian", "Japanese"],
    diets: ["Healthy", "High Protein", "Pescatarian"],
    dishTypes: ["lunch", "healthy"],
    spoonacularScore: 98,
    nutrition: { calories: 480, protein: "36g", carbs: "48g", fat: "16g" }
  },
  {
    id: 125,
    title: "Authentic Thai Chicken Pad Thai",
    image: "https://images.unsplash.com/photo-1559847844-5315695dadae?auto=format&fit=crop&w=800&q=80",
    readyInMinutes: 30,
    servings: 3,
    summary: "Stir-fried rice noodles with tender chicken strips, crispy tofu, eggs, bean sprouts, and garlic chives in a sweet and tangy tamarind sauce.",
    instructions: "1. Stir-fry chicken and tofu in a hot wok.\n2. Add soaked rice noodles and tamarind sauce.\n3. Push aside, scramble eggs, and toss with bean sprouts and crushed peanuts.",
    ingredients: ["8 oz Rice Noodles", "1/2 lb Chicken Breast", "4 oz Tofu", "2 Eggs", "3 tbsp Tamarind Paste", "Bean Sprouts", "Peanuts"],
    cuisines: ["Thai"],
    diets: ["High Protein"],
    dishTypes: ["lunch", "dinner"],
    spoonacularScore: 96,
    nutrition: { calories: 510, protein: "28g", carbs: "62g", fat: "16g" }
  },
  {
    id: 126,
    title: "Tuscan White Bean & Kale Minestrone Soup",
    image: "https://images.unsplash.com/photo-1547592166-23ac45744acd?auto=format&fit=crop&w=800&q=80",
    readyInMinutes: 35,
    servings: 4,
    summary: "Hearty rustic Italian vegetable soup packed with cannellini beans, tender lacinato kale, zucchini, ditalini pasta, and rich tomato broth.",
    instructions: "1. Sauté carrots, onions, celery, and garlic in olive oil.\n2. Add tomatoes, broth, and herbs; simmer for 15 mins.\n3. Add beans, kale, and pasta; simmer until pasta is tender.",
    ingredients: ["1 can Cannellini Beans", "1 can Diced Tomatoes", "4 cups Vegetable Broth", "Kale", "Zucchini", "Ditalini Pasta", "Parmesan"],
    cuisines: ["Italian"],
    diets: ["Vegetarian", "Healthy"],
    dishTypes: ["lunch", "soup"],
    spoonacularScore: 93,
    nutrition: { calories: 290, protein: "12g", carbs: "48g", fat: "5g" }
  },
  {
    id: 127,
    title: "Baja Style Crispy Fish Tacos with Lime Crema",
    image: "https://images.unsplash.com/photo-1512838243191-e81e88cc8912?auto=format&fit=crop&w=800&q=80",
    readyInMinutes: 25,
    servings: 3,
    summary: "Crispy beer-battered wild cod tucked inside warm corn tortillas with crunchy shredded red cabbage slaw, fresh pico de gallo, and zesty cilantro-lime crema.",
    instructions: "1. Dip cod fillets in beer batter and fry until golden and crispy.\n2. Warm corn tortillas on a skillet.\n3. Assemble tacos with crispy cod, cabbage slaw, pico de gallo, and lime crema.",
    ingredients: ["1 lb Cod Fillets", "1 cup Flour & Beer Batter", "8 Corn Tortillas", "Shredded Cabbage", "Lime Crema", "Pico de Gallo"],
    cuisines: ["Mexican"],
    diets: ["Pescatarian", "High Protein"],
    dishTypes: ["lunch"],
    spoonacularScore: 95,
    nutrition: { calories: 430, protein: "24g", carbs: "44g", fat: "17g" }
  },
  {
    id: 128,
    title: "Vietnamese Lemongrass Grilled Chicken Banh Mi",
    image: "https://images.unsplash.com/photo-1528735602780-2552fd46c7af?auto=format&fit=crop&w=800&q=80",
    readyInMinutes: 25,
    servings: 2,
    summary: "Crusty French baguette stuffed with lemongrass-marinated grilled chicken, pickled daikon and carrots, fresh cilantro, cucumber ribbons, and spicy mayo.",
    instructions: "1. Marinate and grill lemongrass chicken cutlets.\n2. Slice warm crisp baguettes.\n3. Layer with pate, spicy mayo, grilled chicken, pickled daikon, cucumber, cilantro, and sliced jalapenos.",
    ingredients: ["2 French Baguettes", "2 Chicken Thighs (lemongrass marinated)", "Pickled Daikon & Carrots", "Cucumbers", "Fresh Cilantro", "Jalapenos", "Mayo"],
    cuisines: ["Vietnamese"],
    diets: ["High Protein"],
    dishTypes: ["lunch", "sandwich"],
    spoonacularScore: 96,
    nutrition: { calories: 490, protein: "32g", carbs: "52g", fat: "17g" }
  },
  {
    id: 129,
    title: "Roasted Tomato & Basil Bisque with Grilled Cheese",
    image: "https://images.unsplash.com/photo-1547592166-23ac45744acd?auto=format&fit=crop&w=800&q=80",
    readyInMinutes: 30,
    servings: 3,
    summary: "Velvety roasted Roma tomato and garlic soup finished with fresh cream and basil, served alongside a sharp cheddar sourdough grilled cheese sandwich.",
    instructions: "1. Roast tomatoes, onions, and garlic at 400°F for 20 minutes.\n2. Blend with vegetable broth, fresh basil, and cream until velvety.\n3. Grill sourdough sandwich filled with sharp cheddar and gruyere until melted.",
    ingredients: ["2 lbs Roma Tomatoes", "1 Onion & 5 Garlic Cloves", "2 cups Vegetable Broth", "1/2 cup Cream", "Fresh Basil", "Sourdough & Sharp Cheddar"],
    cuisines: ["American"],
    diets: ["Vegetarian"],
    dishTypes: ["lunch", "soup"],
    spoonacularScore: 94,
    nutrition: { calories: 480, protein: "16g", carbs: "46g", fat: "26g" }
  },
  {
    id: 130,
    title: "Teriyaki Glazed Salmon & Broccoli Rice Bowl",
    image: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=800&q=80",
    readyInMinutes: 20,
    servings: 2,
    summary: "Tender pan-seared salmon fillet brushed with homemade sweet teriyaki glaze, served over steamed jasmine rice with tender broccoli florets and sesame.",
    instructions: "1. Pan-sear salmon fillets for 4 minutes per side.\n2. Simmer soy sauce, mirin, and brown sugar until glossy glaze forms; brush over salmon.\n3. Serve over warm jasmine rice with steamed broccoli and sesame seeds.",
    ingredients: ["2 Salmon Fillets", "2 cups Jasmine Rice", "2 cups Steamed Broccoli", "3 tbsp Teriyaki Sauce", "Sesame Seeds", "Scallions"],
    cuisines: ["Japanese"],
    diets: ["High Protein", "Pescatarian"],
    dishTypes: ["lunch", "healthy"],
    spoonacularScore: 96,
    nutrition: { calories: 510, protein: "36g", carbs: "52g", fat: "18g" }
  },

  // ==========================================
  // DINNER DISHES (20+ Dishes)
  // ==========================================
  {
    id: 141,
    title: "Creamy Tuscan Garlic Herb Chicken",
    image: "https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?auto=format&fit=crop&w=800&q=80",
    readyInMinutes: 30,
    servings: 4,
    summary: "Golden pan-seared chicken cutlets bathed in a luscious garlic, sun-dried tomato, baby spinach, and parmesan cream sauce.",
    instructions: "1. Pan-sear seasoned chicken breasts until golden brown; set aside.\n2. Sauté garlic and sun-dried tomatoes in butter.\n3. Add cream, broth, and parmesan; simmer until rich.\n4. Fold in spinach and return chicken to pan. Serve over pasta.",
    ingredients: ["4 Chicken Breasts", "1 cup Heavy Cream", "1/2 cup Chicken Broth", "Sun-Dried Tomatoes", "Spinach", "Parmesan", "Garlic"],
    cuisines: ["Italian"],
    diets: ["High Protein", "Keto"],
    dishTypes: ["dinner"],
    spoonacularScore: 97,
    nutrition: { calories: 490, protein: "42g", carbs: "8g", fat: "32g" }
  },
  {
    id: 142,
    title: "Herb Butter Basted Filet Mignon",
    image: "https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=800&q=80",
    readyInMinutes: 25,
    servings: 2,
    summary: "Tender beef tenderloin steaks pan-seared in a hot cast iron skillet and basted with foaming garlic, rosemary, and thyme butter.",
    instructions: "1. Sear steaks in hot skillet for 3 mins per side.\n2. Add butter, garlic, rosemary, and thyme to skillet.\n3. Spoon foaming herb butter continuously over steaks until medium-rare.\n4. Rest 7 minutes before serving.",
    ingredients: ["2 Filet Mignon Steaks", "3 tbsp Butter", "4 cloves Garlic", "Fresh Rosemary & Thyme", "Kosher Salt & Black Pepper"],
    cuisines: ["French", "American"],
    diets: ["High Protein", "Keto", "Gluten Free"],
    dishTypes: ["dinner"],
    spoonacularScore: 98,
    nutrition: { calories: 540, protein: "48g", carbs: "1g", fat: "38g" }
  },
  {
    id: 143,
    title: "Authentic Indian Butter Chicken & Basmati",
    image: "https://images.unsplash.com/photo-1588166524941-3bf61a9c41db?auto=format&fit=crop&w=800&q=80",
    readyInMinutes: 40,
    servings: 4,
    summary: "Tender marinated chicken pieces charred and simmered in a silky, aromatic tomato, cream, butter, and fenugreek masala sauce.",
    instructions: "1. Marinate and sear chicken thighs until charred.\n2. Sauté onions, garlic, ginger, and tomato puree.\n3. Blend sauce, stir in cream, butter, and fenugreek.\n4. Add chicken and simmer for 8 minutes. Serve with basmati rice.",
    ingredients: ["1.5 lbs Chicken Thighs", "1 can Tomato Puree", "1/2 cup Cream", "4 tbsp Butter", "Garam Masala", "Ginger & Garlic", "Basmati Rice"],
    cuisines: ["Indian"],
    diets: ["High Protein", "Gluten Free"],
    dishTypes: ["dinner", "curry"],
    spoonacularScore: 96,
    nutrition: { calories: 560, protein: "38g", carbs: "16g", fat: "39g" }
  },
  {
    id: 144,
    title: "Pan-Seared Salmon with Lemon Herb Butter",
    image: "https://images.unsplash.com/photo-1467003909585-2f8a72700288?auto=format&fit=crop&w=800&q=80",
    readyInMinutes: 20,
    servings: 2,
    summary: "Crispy skin-on wild Atlantic salmon fillets seared to perfection and topped with a bright lemon caper butter sauce, served with asparagus.",
    instructions: "1. Crisp salmon skin-side down in hot skillet for 5 minutes.\n2. Flip and cook for 2 minutes.\n3. Add butter, lemon juice, garlic, and capers; spoon over salmon.",
    ingredients: ["2 Salmon Fillets", "2 tbsp Butter", "1 Lemon", "1 tbsp Capers", "2 cloves Garlic", "Asparagus", "Fresh Parsley"],
    cuisines: ["Mediterranean"],
    diets: ["Healthy", "High Protein", "Keto", "Pescatarian"],
    dishTypes: ["dinner", "seafood"],
    spoonacularScore: 97,
    nutrition: { calories: 440, protein: "36g", carbs: "4g", fat: "31g" }
  },
  {
    id: 145,
    title: "Classic Italian Lasagna Bolognese",
    image: "https://images.unsplash.com/photo-1574894709920-11b28e7367e3?auto=format&fit=crop&w=800&q=80",
    readyInMinutes: 60,
    servings: 6,
    summary: "Layers of egg pasta sheets, slow-simmered beef and pork Bolognese ragù, creamy bechamel sauce, mozzarella, and aged Parmigiano Reggiano.",
    instructions: "1. Simmer beef and sausage bolognese with tomatoes and wine for 45 mins.\n2. Prepare creamy bechamel sauce.\n3. Layer bolognese, pasta sheets, bechamel, and mozzarella in baking dish.\n4. Bake at 375°F for 40 minutes until golden and bubbling.",
    ingredients: ["12 Lasagna Sheets", "1 lb Ground Beef & Sausage", "Crushed Tomatoes", "Bechamel Sauce", "Mozzarella & Parmesan", "Red Wine"],
    cuisines: ["Italian"],
    diets: ["High Protein"],
    dishTypes: ["dinner", "pasta"],
    spoonacularScore: 95,
    nutrition: { calories: 580, protein: "34g", carbs: "42g", fat: "30g" }
  },
  {
    id: 146,
    title: "Thai Green Coconut Chicken Curry",
    image: "https://images.unsplash.com/photo-1455619452474-d2be8b1e70cd?auto=format&fit=crop&w=800&q=80",
    readyInMinutes: 30,
    servings: 4,
    summary: "Aromatic Thai green curry simmered with tender chicken slices, bamboo shoots, Thai eggplants, kaffir lime leaves, and sweet Thai basil.",
    instructions: "1. Fry green curry paste in coconut cream.\n2. Add sliced chicken and cook for 3 minutes.\n3. Add coconut milk, bamboo shoots, and bell peppers; simmer for 10 mins.\n4. Stir in fresh Thai basil and serve with jasmine rice.",
    ingredients: ["1.5 lbs Chicken", "1 can Coconut Milk", "3 tbsp Green Curry Paste", "Bamboo Shoots", "Bell Pepper", "Thai Basil", "Fish Sauce"],
    cuisines: ["Thai"],
    diets: ["Gluten Free", "High Protein"],
    dishTypes: ["dinner", "curry"],
    spoonacularScore: 94,
    nutrition: { calories: 470, protein: "32g", carbs: "12g", fat: "32g" }
  },
  {
    id: 147,
    title: "Spanish Seafood Paella Valenciana",
    image: "https://images.unsplash.com/photo-1534080564583-6be75777b70a?auto=format&fit=crop&w=800&q=80",
    readyInMinutes: 45,
    servings: 4,
    summary: "Saffron-infused Bomba rice slowly cooked with succulent jumbo shrimp, mussels, calamari, sweet bell peppers, and peas with a crispy socarrat crust.",
    instructions: "1. Sauté onions, garlic, and bell peppers in a paella pan.\n2. Stir in Bomba rice and saffron-infused seafood broth.\n3. Arrange shrimp, mussels, and calamari over rice.\n4. Simmer undisturbed until liquid is absorbed and crispy socarrat crust forms on bottom.",
    ingredients: ["1.5 cups Bomba Rice", "1/2 lb Jumbo Shrimp", "1/2 lb Mussels", "1/2 lb Calamari", "Saffron Threads", "4 cups Seafood Stock", "Sweet Peas & Lemon"],
    cuisines: ["Spanish"],
    diets: ["Pescatarian", "Gluten Free"],
    dishTypes: ["dinner", "seafood"],
    spoonacularScore: 97,
    nutrition: { calories: 490, protein: "34g", carbs: "56g", fat: "14g" }
  },
  {
    id: 148,
    title: "Braised Beef Short Ribs in Red Wine Reduction",
    image: "https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=800&q=80",
    readyInMinutes: 150,
    servings: 4,
    summary: "Melt-in-your-mouth bone-in beef short ribs slow-braised for hours in Cabernet Sauvignon, aromatic root vegetables, and fresh herbs.",
    instructions: "1. Brown seasoned short ribs deeply on all sides.\n2. Sauté carrots, celery, onions, and tomato paste.\n3. Pour in red wine and beef stock; return ribs and herbs.\n4. Cover and braise at 325°F for 2.5 hours until fork tender.\n5. Reduce braising liquid into rich glaze and serve over creamy mashed potatoes.",
    ingredients: ["4 Bone-In Beef Short Ribs", "2 cups Cabernet Sauvignon Wine", "2 cups Beef Bone Broth", "Carrots, Celery, Onions", "Fresh Rosemary & Thyme", "Mashed Potatoes"],
    cuisines: ["French"],
    diets: ["High Protein", "Gluten Free"],
    dishTypes: ["dinner"],
    spoonacularScore: 99,
    nutrition: { calories: 640, protein: "52g", carbs: "12g", fat: "42g" }
  },
  {
    id: 149,
    title: "Chicken Tikka Masala with Garlic Naan",
    image: "https://images.unsplash.com/photo-1588166524941-3bf61a9c41db?auto=format&fit=crop&w=800&q=80",
    readyInMinutes: 35,
    servings: 4,
    summary: "Yogurt-marinated grilled chicken chunks in a rich, spiced creamy tomato sauce with notes of cumin, coriander, and garam masala.",
    instructions: "1. Skewer and broil spiced marinated chicken until charred.\n2. Simmer tomato, cream, onion, and spice gravy for 12 minutes.\n3. Add grilled chicken pieces into curry and simmer for 5 minutes.\n4. Serve hot with garlic butter naan.",
    ingredients: ["1.5 lbs Chicken Breast", "1 can Tomato Sauce", "1/2 cup Heavy Cream", "Yogurt", "Garam Masala, Cumin, Turmeric", "Garlic Butter Naan"],
    cuisines: ["Indian"],
    diets: ["High Protein"],
    dishTypes: ["dinner", "curry"],
    spoonacularScore: 96,
    nutrition: { calories: 530, protein: "38g", carbs: "22g", fat: "32g" }
  },
  {
    id: 150,
    title: "Creamy Garlic Parmesan Shrimp Linguine",
    image: "https://images.unsplash.com/photo-1621996346565-e3d5d6281728?auto=format&fit=crop&w=800&q=80",
    readyInMinutes: 20,
    servings: 3,
    summary: "Succulent jumbo shrimp sautéed in garlic butter and tossed with al dente linguine in a velvety parmesan white wine cream sauce.",
    instructions: "1. Cook linguine in salted boiling water.\n2. Sauté seasoned shrimp in butter and olive oil for 2 mins per side; remove.\n3. Deglaze skillet with white wine, simmer cream and garlic.\n4. Stir in parmesan and toss with linguine and shrimp.",
    ingredients: ["1 lb Jumbo Shrimp", "8 oz Linguine", "1 cup Heavy Cream", "1/2 cup Parmesan", "4 cloves Garlic", "1/4 cup White Wine", "Fresh Parsley"],
    cuisines: ["Italian"],
    diets: ["Pescatarian", "High Protein"],
    dishTypes: ["dinner", "pasta"],
    spoonacularScore: 95,
    nutrition: { calories: 520, protein: "32g", carbs: "46g", fat: "24g" }
  },

  // ==========================================
  // DESSERT DISHES (20+ Dishes)
  // ==========================================
  {
    id: 161,
    title: "Rich Decadent Chocolate Lava Cake",
    image: "https://images.unsplash.com/photo-1606313564200-e75d5e30476c?auto=format&fit=crop&w=800&q=80",
    readyInMinutes: 25,
    servings: 2,
    summary: "Warm individual dark chocolate cakes with a luscious, flowing molten chocolate center, dusted with powdered sugar and served with vanilla gelato.",
    instructions: "1. Melt dark chocolate and butter together.\n2. Whisk eggs and sugar until frothy; fold in chocolate and flour.\n3. Pour into buttered ramekins.\n4. Bake at 425°F for 12 minutes.\n5. Invert onto plates and serve hot with vanilla gelato.",
    ingredients: ["4 oz Dark Chocolate (70%)", "1/2 cup Butter", "2 Eggs & 2 Yolks", "1/4 cup Sugar", "2 tbsp Flour", "Vanilla Gelato"],
    cuisines: ["French"],
    diets: ["Vegetarian"],
    dishTypes: ["dessert"],
    spoonacularScore: 98,
    nutrition: { calories: 460, protein: "6g", carbs: "38g", fat: "32g" }
  },
  {
    id: 162,
    title: "Classic Italian Coffee Tiramisu",
    image: "https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?auto=format&fit=crop&w=800&q=80",
    readyInMinutes: 30,
    servings: 6,
    summary: "Layers of delicate Italian savoiardi ladyfingers soaked in rich espresso and dark rum, enveloped in velvety mascarpone cream and dusted with Dutch cocoa.",
    instructions: "1. Whisk egg yolks, sugar, and mascarpone with whipped cream.\n2. Dip ladyfingers briefly in espresso and rum.\n3. Layer soaked ladyfingers and mascarpone cream in dish.\n4. Dust generously with cocoa powder and chill for 4 hours.",
    ingredients: ["24 Ladyfingers", "16 oz Mascarpone", "1 cup Espresso", "3 Egg Yolks", "1/2 cup Sugar", "1 cup Whipping Cream", "Cocoa Powder"],
    cuisines: ["Italian"],
    diets: ["Vegetarian"],
    dishTypes: ["dessert"],
    spoonacularScore: 96,
    nutrition: { calories: 380, protein: "7g", carbs: "36g", fat: "24g" }
  },
  {
    id: 163,
    title: "New York Style Baked Cheesecake",
    image: "https://images.unsplash.com/photo-1533134242443-d4fd215305ad?auto=format&fit=crop&w=800&q=80",
    readyInMinutes: 70,
    servings: 8,
    summary: "Ultra-dense, creamy classic New York style cheesecake with a buttery graham cracker crust and a tart homemade fresh strawberry coulis topping.",
    instructions: "1. Press graham cracker crust into springform pan.\n2. Beat cream cheese, sugar, sour cream, vanilla, and eggs until smooth.\n3. Bake in a water bath at 325°F for 65 minutes.\n4. Chill 6 hours and top with strawberry coulis.",
    ingredients: ["32 oz Cream Cheese", "1.25 cups Sugar", "1 cup Sour Cream", "4 Eggs", "Graham Cracker Crust", "Strawberry Coulis"],
    cuisines: ["American"],
    diets: ["Vegetarian"],
    dishTypes: ["dessert"],
    spoonacularScore: 97,
    nutrition: { calories: 520, protein: "9g", carbs: "44g", fat: "35g" }
  },
  {
    id: 164,
    title: "Vanilla Bean Crème Brûlée",
    image: "https://images.unsplash.com/photo-1470124182917-cc6e71b22ecc?auto=format&fit=crop&w=800&q=80",
    readyInMinutes: 45,
    servings: 4,
    summary: "Rich, silky French vanilla custard topped with a shatteringly crisp layer of freshly torched caramelized sugar.",
    instructions: "1. Whisk hot vanilla cream into egg yolks and sugar.\n2. Strain into ramekins and bake in water bath at 325°F for 35 mins.\n3. Chill, sprinkle sugar on top, and caramelize with a blowtorch.",
    ingredients: ["2 cups Heavy Cream", "1 Vanilla Bean", "5 Egg Yolks", "1/3 cup Sugar", "Cane Sugar (for torching)"],
    cuisines: ["French"],
    diets: ["Vegetarian", "Gluten Free"],
    dishTypes: ["dessert"],
    spoonacularScore: 96,
    nutrition: { calories: 410, protein: "5g", carbs: "26g", fat: "33g" }
  },
  {
    id: 165,
    title: "Spanish Churros with Warm Dulce de Leche",
    image: "https://images.unsplash.com/photo-1624353365286-3f8d62daad51?auto=format&fit=crop&w=800&q=80",
    readyInMinutes: 30,
    servings: 4,
    summary: "Golden piped choux pastry fried until crispy, tossed in fragrant cinnamon sugar, and served with velvety warm dulce de leche and chocolate dip.",
    instructions: "1. Prepare choux dough on stovetop, beat in eggs.\n2. Pipe star-shaped strips into 375°F oil; fry until golden brown.\n3. Roll immediately in cinnamon sugar and serve with warm dulce de leche.",
    ingredients: ["1 cup Flour", "1 cup Water", "1/3 cup Butter", "2 Eggs", "Cinnamon Sugar", "Dulce de Leche & Dark Chocolate"],
    cuisines: ["Spanish"],
    diets: ["Vegetarian"],
    dishTypes: ["dessert"],
    spoonacularScore: 93,
    nutrition: { calories: 370, protein: "5g", carbs: "48g", fat: "18g" }
  },
  {
    id: 166,
    title: "Classic French Apple Tarte Tatin",
    image: "https://images.unsplash.com/photo-1535141192574-5d4897c13136?auto=format&fit=crop&w=800&q=80",
    readyInMinutes: 50,
    servings: 6,
    summary: "Caramelized Honeycrisp apples baked upside down under flaky puff pastry, then inverted to reveal glossy amber apple wedges.",
    instructions: "1. Cook apple wedges in butter and sugar in a skillet until deeply caramelized.\n2. Drape puff pastry sheet over apples, tucking edges.\n3. Bake at 400°F for 25 minutes until pastry is puffed and golden.\n4. Invert onto a serving platter and serve warm with vanilla ice cream.",
    ingredients: ["6 Honeycrisp Apples", "1 sheet Puff Pastry", "1/2 cup Butter", "3/4 cup Sugar", "Vanilla Ice Cream"],
    cuisines: ["French"],
    diets: ["Vegetarian"],
    dishTypes: ["dessert"],
    spoonacularScore: 95,
    nutrition: { calories: 340, protein: "3g", carbs: "46g", fat: "17g" }
  },
  {
    id: 167,
    title: "Key Lime Pie with Graham Cracker Crust",
    image: "https://images.unsplash.com/photo-1533134242443-d4fd215305ad?auto=format&fit=crop&w=800&q=80",
    readyInMinutes: 35,
    servings: 8,
    summary: "Authentic Florida Key lime pie with a tart and creamy custard filling in a buttery graham crust, crowned with fresh whipped cream.",
    instructions: "1. Whisk sweetened condensed milk, egg yolks, and fresh Key lime juice.\n2. Pour into pre-baked graham cracker crust.\n3. Bake at 350°F for 15 minutes to set.\n4. Chill for 4 hours and pipe fresh whipped cream rosettes on top.",
    ingredients: ["1 can Sweetened Condensed Milk", "1/2 cup Fresh Key Lime Juice", "4 Egg Yolks", "Graham Cracker Crust", "Whipped Cream"],
    cuisines: ["American"],
    diets: ["Vegetarian"],
    dishTypes: ["dessert"],
    spoonacularScore: 94,
    nutrition: { calories: 360, protein: "6g", carbs: "48g", fat: "16g" }
  },
  {
    id: 168,
    title: "Vanilla Raspberry Panna Cotta",
    image: "https://images.unsplash.com/photo-1470124182917-cc6e71b22ecc?auto=format&fit=crop&w=800&q=80",
    readyInMinutes: 20,
    servings: 4,
    summary: "Silky Italian vanilla bean cream set to a delicate wobble, topped with a bright homemade ruby raspberry coulis and fresh mint.",
    instructions: "1. Bloom gelatin in cold water.\n2. Heat cream, milk, sugar, and vanilla bean until warm; dissolve gelatin.\n3. Pour into glasses and chill for 4 hours.\n4. Top with fresh raspberry puree before serving.",
    ingredients: ["1.5 cups Heavy Cream", "1/2 cup Whole Milk", "1/3 cup Sugar", "1 Vanilla Bean", "2 tsp Gelatin", "Fresh Raspberry Coulis"],
    cuisines: ["Italian"],
    diets: ["Gluten Free"],
    dishTypes: ["dessert"],
    spoonacularScore: 96,
    nutrition: { calories: 310, protein: "4g", carbs: "22g", fat: "24g" }
  },
  {
    id: 169,
    title: "Honey Pistachio Turkish Baklava",
    image: "https://images.unsplash.com/photo-1593001874117-c99c800e3eb7?auto=format&fit=crop&w=800&q=80",
    readyInMinutes: 60,
    servings: 12,
    summary: "Crispy layers of buttered paper-thin phyllo pastry stuffed with chopped Antep pistachios and drenched in lemon-infused honey syrup.",
    instructions: "1. Layer 20 buttered phyllo sheets, chopped pistachios, and 20 more buttered sheets.\n2. Cut into diamond shapes and bake at 350°F for 45 mins until golden.\n3. Pour cooled honey syrup over hot baklava immediately.",
    ingredients: ["1 roll Phyllo Pastry", "2 cups Shelled Pistachios, finely chopped", "1 cup Melted Butter", "1 cup Honey & Lemon Syrup"],
    cuisines: ["Turkish", "Middle Eastern"],
    diets: ["Vegetarian"],
    dishTypes: ["dessert"],
    spoonacularScore: 97,
    nutrition: { calories: 330, protein: "6g", carbs: "38g", fat: "18g" }
  },
  {
    id: 170,
    title: "Warm Fudgy Double Chocolate Brownies",
    image: "https://images.unsplash.com/photo-1606313564200-e75d5e30476c?auto=format&fit=crop&w=800&q=80",
    readyInMinutes: 35,
    servings: 9,
    summary: "Chewy, ultra-fudgy brownies packed with melted dark chocolate chunks and toasted walnuts, with a shiny crackly crinkle top.",
    instructions: "1. Whisk melted butter and sugars vigorously with eggs for shiny top.\n2. Fold in melted dark chocolate, cocoa powder, and flour.\n3. Fold in chocolate chunks and walnuts.\n4. Bake at 350°F for 24 minutes until set.",
    ingredients: ["1/2 cup Melted Butter", "1 cup Sugar", "2 Eggs", "1/2 cup Cocoa Powder", "1/2 cup Flour", "1 cup Dark Chocolate Chunks", "Walnuts"],
    cuisines: ["American"],
    diets: ["Vegetarian"],
    dishTypes: ["dessert"],
    spoonacularScore: 95,
    nutrition: { calories: 320, protein: "4g", carbs: "42g", fat: "17g" }
  },

  // ==========================================
  // VEGETARIAN DISHES (20+ Dishes)
  // ==========================================
  {
    id: 181,
    title: "Authentic North Indian Palak Paneer",
    image: "https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=800&q=80",
    readyInMinutes: 30,
    servings: 4,
    summary: "Soft homemade paneer cheese cubes simmered in a vibrant, creamy spiced spinach gravy infused with garlic, cumin, and garam masala.",
    instructions: "1. Blanch and puree fresh spinach.\n2. Lightly fry paneer cubes in ghee.\n3. Sauté onions, garlic, ginger, tomatoes, and spices.\n4. Add spinach puree and cream; simmer with paneer cubes for 5 minutes.",
    ingredients: ["250g Paneer Cheese", "500g Fresh Spinach", "2 tbsp Ghee", "1 Onion", "Ginger & Garlic", "Tomatoes", "Heavy Cream", "Garam Masala"],
    cuisines: ["Indian"],
    diets: ["Vegetarian", "Gluten Free", "Healthy"],
    dishTypes: ["dinner", "curry", "vegetarian"],
    spoonacularScore: 96,
    nutrition: { calories: 360, protein: "18g", carbs: "12g", fat: "27g" }
  },
  {
    id: 182,
    title: "Italian Baked Eggplant Parmesan (Melanzane)",
    image: "https://images.unsplash.com/photo-1625944230945-1b7dd3b949ab?auto=format&fit=crop&w=800&q=80",
    readyInMinutes: 45,
    servings: 4,
    summary: "Crispy breaded eggplant cutlets baked in layers of rustic San Marzano tomato marinara, melted mozzarella, and fragrant fresh basil.",
    instructions: "1. Bread and bake eggplant slices until crispy.\n2. Layer marinara sauce, crispy eggplant, fresh mozzarella, and basil in a baking dish.\n3. Top with parmesan and bake at 375°F for 25 minutes until bubbling.",
    ingredients: ["2 Globe Eggplants", "2 cups Breadcrumbs", "2 cups Marinara Sauce", "8 oz Mozzarella", "Parmesan", "Fresh Basil"],
    cuisines: ["Italian"],
    diets: ["Vegetarian"],
    dishTypes: ["dinner", "vegetarian"],
    spoonacularScore: 95,
    nutrition: { calories: 410, protein: "20g", carbs: "42g", fat: "19g" }
  },
  {
    id: 183,
    title: "Creamy Wild Mushroom & Truffle Risotto",
    image: "https://images.unsplash.com/photo-1633964913295-ceb43826e7c9?auto=format&fit=crop&w=800&q=80",
    readyInMinutes: 35,
    servings: 4,
    summary: "Al dente Italian Carnaroli arborio rice slowly simmered with shallots, white wine, rich vegetable broth, sautéed wild porcini mushrooms, and black truffle oil.",
    instructions: "1. Toast Arborio rice in butter with shallots.\n2. Deglaze with white wine and add warm broth ladle by ladle while stirring.\n3. Fold in sautéed wild mushrooms, parmesan, and truffle oil.",
    ingredients: ["1.5 cups Arborio Rice", "1 lb Wild Mushrooms", "4 cups Vegetable Broth", "1/2 cup White Wine", "Parmesan", "Truffle Oil"],
    cuisines: ["Italian"],
    diets: ["Vegetarian", "Gluten Free"],
    dishTypes: ["dinner", "vegetarian"],
    spoonacularScore: 97,
    nutrition: { calories: 420, protein: "11g", carbs: "62g", fat: "14g" }
  },
  {
    id: 184,
    title: "Jumbo Spinach & Ricotta Stuffed Pasta Shells",
    image: "https://images.unsplash.com/photo-1551183053-bf91a1d81141?auto=format&fit=crop&w=800&q=80",
    readyInMinutes: 40,
    servings: 4,
    summary: "Tender jumbo pasta shells stuffed with creamy whole-milk ricotta, sautéed baby spinach, parmesan, and baked over garlic marinara with bubbly mozzarella.",
    instructions: "1. Boil jumbo pasta shells al dente.\n2. Mix ricotta, sautéed spinach, parmesan, egg, and seasoning.\n3. Stuff shells, arrange over marinara in dish, top with mozzarella and bake.",
    ingredients: ["20 Jumbo Pasta Shells", "15 oz Ricotta", "2 cups Mozzarella", "1/2 cup Parmesan", "Spinach", "Marinara Sauce"],
    cuisines: ["Italian"],
    diets: ["Vegetarian"],
    dishTypes: ["dinner", "vegetarian", "pasta"],
    spoonacularScore: 94,
    nutrition: { calories: 440, protein: "24g", carbs: "48g", fat: "18g" }
  },
  {
    id: 185,
    title: "Traditional Neapolitan Pizza Margherita",
    image: "https://images.unsplash.com/photo-1604382355076-af4b0eb60143?auto=format&fit=crop&w=800&q=80",
    readyInMinutes: 20,
    servings: 2,
    summary: "Hand-stretched artisan pizza dough topped with crushed San Marzano tomatoes, fresh buffalo mozzarella, aromatic sweet basil leaves, and extra virgin olive oil.",
    instructions: "1. Stretch pizza dough into a 12-inch round.\n2. Spread crushed San Marzano tomatoes and buffalo mozzarella.\n3. Bake on a hot pizza stone at 500°F for 8 mins; finish with fresh basil and olive oil.",
    ingredients: ["1 Pizza Dough ball", "1/2 cup San Marzano Tomatoes", "6 oz Buffalo Mozzarella", "Fresh Basil", "Extra Virgin Olive Oil"],
    cuisines: ["Italian"],
    diets: ["Vegetarian"],
    dishTypes: ["dinner", "vegetarian"],
    spoonacularScore: 98,
    nutrition: { calories: 480, protein: "20g", carbs: "58g", fat: "18g" }
  },
  {
    id: 186,
    title: "Slow-Cooked Punjabi Dal Makhani",
    image: "https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&w=800&q=80",
    readyInMinutes: 50,
    servings: 4,
    summary: "Creamy whole black lentils and red kidney beans slow-cooked with butter, cream, ginger, and aromatic North Indian spices.",
    instructions: "1. Pressure cook black lentils and kidney beans until tender.\n2. Sauté ginger, garlic, and tomato puree in butter.\n3. Add lentils and simmer on low for 35 mins; finish with cream and garam masala.",
    ingredients: ["1 cup Black Urad Dal", "1/4 cup Kidney Beans", "3 tbsp Butter", "Tomato Puree", "Cream", "Ginger & Garlic", "Garam Masala"],
    cuisines: ["Indian"],
    diets: ["Vegetarian", "Gluten Free", "Healthy"],
    dishTypes: ["dinner", "curry", "vegetarian"],
    spoonacularScore: 95,
    nutrition: { calories: 340, protein: "16g", carbs: "44g", fat: "12g" }
  },
  {
    id: 187,
    title: "Thai Red Coconut Curry with Crispy Tofu",
    image: "https://images.unsplash.com/photo-1455619452474-d2be8b1e70cd?auto=format&fit=crop&w=800&q=80",
    readyInMinutes: 25,
    servings: 3,
    summary: "Crispy pan-fried firm tofu cubes simmered in a velvety red coconut curry with sugar snap peas, baby corn, bamboo shoots, and Thai basil.",
    instructions: "1. Pan-fry pressed tofu cubes until crispy.\n2. Sauté red curry paste in coconut cream.\n3. Add coconut milk, vegetables, and crispy tofu; simmer for 8 minutes.\n4. Garnish with Thai basil and serve over jasmine rice.",
    ingredients: ["1 block Firm Tofu", "1 can Coconut Milk", "3 tbsp Red Curry Paste", "Snap Peas & Baby Corn", "Thai Basil", "Soy Sauce"],
    cuisines: ["Thai"],
    diets: ["Vegan", "Vegetarian", "Gluten Free", "Healthy"],
    dishTypes: ["dinner", "curry", "vegetarian"],
    spoonacularScore: 96,
    nutrition: { calories: 390, protein: "16g", carbs: "22g", fat: "28g" }
  },
  {
    id: 188,
    title: "Classic Greek Spanakopita (Spinach & Feta Pie)",
    image: "https://images.unsplash.com/photo-1593001874117-c99c800e3eb7?auto=format&fit=crop&w=800&q=80",
    readyInMinutes: 45,
    servings: 6,
    summary: "Flaky, golden-baked layers of buttered phyllo pastry filled with seasoned spinach, Greek feta cheese, eggs, dill, and scallions.",
    instructions: "1. Sauté spinach and scallions; drain and mix with feta, ricotta, eggs, and dill.\n2. Layer buttered phyllo pastry sheets in a baking dish.\n3. Spread spinach filling and top with more buttered phyllo.\n4. Bake at 375°F for 35 minutes until crisp and golden brown.",
    ingredients: ["1 roll Phyllo Dough", "1 lb Fresh Spinach", "1.5 cups Greek Feta Cheese", "1/2 cup Ricotta", "2 Eggs", "Fresh Dill & Butter"],
    cuisines: ["Greek", "Mediterranean"],
    diets: ["Vegetarian"],
    dishTypes: ["lunch", "dinner", "vegetarian"],
    spoonacularScore: 94,
    nutrition: { calories: 370, protein: "14g", carbs: "32g", fat: "22g" }
  },
  {
    id: 189,
    title: "French Provençal Roasted Ratatouille",
    image: "https://images.unsplash.com/photo-1543339308-43e59d6b73a6?auto=format&fit=crop&w=800&q=80",
    readyInMinutes: 50,
    servings: 4,
    summary: "Artfully arranged concentric rings of zucchini, yellow squash, Japanese eggplant, and tomatoes baked over a rich bell pepper and garlic piperade.",
    instructions: "1. Spread bell pepper and tomato piperade on bottom of skillet.\n2. Arrange sliced zucchini, eggplant, squash, and tomatoes in alternating spirals.\n3. Drizzle with garlic-herb olive oil and cover with parchment.\n4. Bake at 375°F for 40 minutes until vegetables are tender.",
    ingredients: ["2 Zucchini & 2 Yellow Squash", "2 Japanese Eggplants", "4 Roma Tomatoes", "Bell Pepper Piperade", "Garlic, Thyme, Olive Oil"],
    cuisines: ["French"],
    diets: ["Vegan", "Vegetarian", "Healthy", "Gluten Free"],
    dishTypes: ["dinner", "vegetarian", "healthy"],
    spoonacularScore: 95,
    nutrition: { calories: 180, protein: "5g", carbs: "24g", fat: "8g" }
  },
  {
    id: 190,
    title: "Potato Gnocchi with Brown Butter & Crispy Sage",
    image: "https://images.unsplash.com/photo-1621996346565-e3d5d6281728?auto=format&fit=crop&w=800&q=80",
    readyInMinutes: 20,
    servings: 2,
    summary: "Pillowy handmade potato gnocchi seared until lightly golden, tossed in nutty hazelnut brown butter, crispy fresh sage leaves, and parmesan.",
    instructions: "1. Boil gnocchi until they float to the surface (2 mins); drain.\n2. Melt butter in a skillet over medium heat until nutty and foaming.\n3. Add fresh sage leaves and fry until crisp.\n4. Add boiled gnocchi to skillet and toss until slightly toasted.\n5. Finish with grated Parmigiano Reggiano.",
    ingredients: ["1 lb Potato Gnocchi", "4 tbsp Butter", "12 Fresh Sage Leaves", "1/2 cup Grated Parmesan", "Salt & Black Pepper"],
    cuisines: ["Italian"],
    diets: ["Vegetarian"],
    dishTypes: ["dinner", "vegetarian", "pasta"],
    spoonacularScore: 93,
    nutrition: { calories: 420, protein: "10g", carbs: "56g", fat: "18g" }
  },

  // ==========================================
  // HEALTHY DISHES (20+ Dishes)
  // ==========================================
  {
    id: 201,
    title: "Fresh Avocado & Quinoa Garden Bowl",
    image: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=800&q=80",
    readyInMinutes: 20,
    servings: 2,
    summary: "Nutrient-packed superfood salad bowl with ripe avocados, fluffy tri-color quinoa, roasted sweet potatoes, cherry tomatoes, cucumbers, and creamy lemon tahini dressing.",
    instructions: "1. Cook quinoa and roast diced sweet potatoes.\n2. Assemble bowls with quinoa, sweet potatoes, avocado, tomatoes, and cucumbers.\n3. Drizzle with lemon tahini dressing and toasted pumpkin seeds.",
    ingredients: ["1 cup Quinoa", "1 Avocado", "1 Sweet Potato", "Cherry Tomatoes", "Cucumbers", "Tahini & Lemon Juice", "Pumpkin Seeds"],
    cuisines: ["Healthy"],
    diets: ["Vegan", "Vegetarian", "Healthy", "Gluten Free"],
    dishTypes: ["salad", "healthy"],
    spoonacularScore: 97,
    nutrition: { calories: 380, protein: "12g", carbs: "52g", fat: "16g" }
  },
  {
    id: 202,
    title: "Steamed Ginger Seabass with Bok Choy",
    image: "https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?auto=format&fit=crop&w=800&q=80",
    readyInMinutes: 18,
    servings: 2,
    summary: "Delicate fresh seabass fillets gently steamed with julienned fresh ginger, scallions, tender baby bok choy, and light sesame-tamari sauce.",
    instructions: "1. Arrange seabass fillets over baby bok choy with ginger and scallions.\n2. Steam covered for 9 minutes until fish flakes easily.\n3. Drizzle with sizzling hot sesame oil and tamari soy sauce.",
    ingredients: ["2 Seabass Fillets", "4 Baby Bok Choy", "Fresh Ginger & Scallions", "Tamari Soy Sauce", "Toasted Sesame Oil"],
    cuisines: ["Asian"],
    diets: ["Healthy", "Gluten Free", "High Protein", "Pescatarian"],
    dishTypes: ["dinner", "healthy"],
    spoonacularScore: 98,
    nutrition: { calories: 290, protein: "34g", carbs: "6g", fat: "14g" }
  },
  {
    id: 203,
    title: "Superfood Kale, Pomegranate & Blueberry Salad",
    image: "https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&w=800&q=80",
    readyInMinutes: 15,
    servings: 3,
    summary: "Tender massaged organic Lacinato kale tossed with sweet pomegranate arils, fresh blueberries, creamy goat cheese, candied walnuts, and apple cider vinaigrette.",
    instructions: "1. Massage chopped kale with olive oil and salt.\n2. Toss with blueberries, pomegranate seeds, walnuts, and goat cheese.\n3. Dress with light apple cider vinaigrette.",
    ingredients: ["1 bunch Kale", "1/2 cup Blueberries", "1/2 cup Pomegranate Seeds", "Goat Cheese", "Walnuts", "Apple Cider Vinaigrette"],
    cuisines: ["Healthy"],
    diets: ["Vegetarian", "Healthy", "Gluten Free"],
    dishTypes: ["salad", "healthy"],
    spoonacularScore: 95,
    nutrition: { calories: 260, protein: "8g", carbs: "24g", fat: "16g" }
  },
  {
    id: 204,
    title: "Golden Turmeric Cauliflower Rice & Grilled Chicken",
    image: "https://images.unsplash.com/photo-1490645935967-10de6ba17061?auto=format&fit=crop&w=800&q=80",
    readyInMinutes: 25,
    servings: 2,
    summary: "Low-carb riced cauliflower sautéed with organic turmeric, garlic, and herbs, served alongside herb-marinated grilled chicken breast.",
    instructions: "1. Grill marinated chicken breasts for 6 mins per side.\n2. Sauté grated cauliflower rice with turmeric, garlic, and olive oil for 5 mins.\n3. Serve sliced chicken over golden rice with almonds and lemon.",
    ingredients: ["1 Head Cauliflower, riced", "2 Chicken Breasts", "1 tsp Ground Turmeric", "Garlic & Olive Oil", "Sliced Almonds", "Parsley"],
    cuisines: ["Healthy"],
    diets: ["Healthy", "High Protein", "Keto", "Gluten Free"],
    dishTypes: ["lunch", "dinner", "healthy"],
    spoonacularScore: 96,
    nutrition: { calories: 340, protein: "38g", carbs: "12g", fat: "14g" }
  },
  {
    id: 205,
    title: "Mediterranean Chickpea & Roasted Vegetable Grain Bowl",
    image: "https://images.unsplash.com/photo-1543339308-43e59d6b73a6?auto=format&fit=crop&w=800&q=80",
    readyInMinutes: 30,
    servings: 3,
    summary: "Spiced crispy roasted chickpeas, tender roasted zucchini, bell peppers, Kalamata olives, and feta cheese over warm farro with tzatziki sauce.",
    instructions: "1. Roast spiced chickpeas, zucchini, and peppers at 400°F for 20 mins.\n2. Assemble bowls with warm cooked farro, roasted veggies, and chickpeas.\n3. Top with Kalamata olives, feta, and tzatziki.",
    ingredients: ["1 can Chickpeas", "1 cup Farro or Brown Rice", "Zucchini & Bell Pepper", "Kalamata Olives", "Feta Cheese", "Tzatziki Sauce"],
    cuisines: ["Mediterranean"],
    diets: ["Vegetarian", "Healthy"],
    dishTypes: ["lunch", "healthy"],
    spoonacularScore: 95,
    nutrition: { calories: 390, protein: "15g", carbs: "56g", fat: "13g" }
  },
  {
    id: 206,
    title: "Grilled Salmon with Lemon Herb Steamed Asparagus",
    image: "https://images.unsplash.com/photo-1467003909585-2f8a72700288?auto=format&fit=crop&w=800&q=80",
    readyInMinutes: 20,
    servings: 2,
    summary: "Wild Omega-3 rich salmon fillet grilled with lemon zest and fresh dill, served alongside tender steamed asparagus spears.",
    instructions: "1. Season salmon with olive oil, lemon zest, garlic, salt, and dill.\n2. Grill for 4-5 minutes per side.\n3. Steam fresh asparagus for 4 minutes.\n4. Serve with fresh lemon wedges.",
    ingredients: ["2 Wild Salmon Fillets", "1 bunch Asparagus", "1 Lemon", "Fresh Dill & Garlic", "Extra Virgin Olive Oil"],
    cuisines: ["Healthy", "Mediterranean"],
    diets: ["Healthy", "High Protein", "Keto", "Gluten Free", "Pescatarian"],
    dishTypes: ["dinner", "healthy", "seafood"],
    spoonacularScore: 98,
    nutrition: { calories: 390, protein: "38g", carbs: "4g", fat: "24g" }
  },
  {
    id: 207,
    title: "Green Goddess Detox Power Smoothie Bowl",
    image: "https://images.unsplash.com/photo-1590080875515-8a3a8dc5735e?auto=format&fit=crop&w=800&q=80",
    readyInMinutes: 10,
    servings: 2,
    summary: "Energizing smoothie bowl blended with organic baby spinach, frozen mango, pineapple, avocado, and spirulina, topped with chia and hemp seeds.",
    instructions: "1. Blend spinach, frozen mango, pineapple, avocado, and coconut water until smooth and creamy.\n2. Pour into bowls.\n3. Top with hemp seeds, chia seeds, and sliced kiwi.",
    ingredients: ["2 cups Baby Spinach", "1 cup Frozen Mango", "1/2 cup Pineapple", "1/2 Avocado", "1 cup Coconut Water", "Hemp & Chia Seeds"],
    cuisines: ["Healthy"],
    diets: ["Vegan", "Vegetarian", "Healthy", "Gluten Free"],
    dishTypes: ["breakfast", "healthy"],
    spoonacularScore: 96,
    nutrition: { calories: 240, protein: "6g", carbs: "42g", fat: "8g" }
  },
  {
    id: 208,
    title: "Moroccan Spiced Lentil & Sweet Potato Stew",
    image: "https://images.unsplash.com/photo-1547592166-23ac45744acd?auto=format&fit=crop&w=800&q=80",
    readyInMinutes: 35,
    servings: 4,
    summary: "Heart-healthy brown lentils simmered with cubed sweet potatoes, fire-roasted tomatoes, cumin, turmeric, and fresh cilantro.",
    instructions: "1. Sauté onions, garlic, ginger, and Moroccan spices in olive oil.\n2. Add brown lentils, sweet potato cubes, tomatoes, and vegetable broth.\n3. Simmer for 25 minutes until lentils and sweet potatoes are tender.",
    ingredients: ["1 cup Brown Lentils", "2 Sweet Potatoes, cubed", "1 can Diced Tomatoes", "4 cups Vegetable Broth", "Cumin, Turmeric, Cinnamon", "Fresh Cilantro"],
    cuisines: ["Middle Eastern", "Healthy"],
    diets: ["Vegan", "Vegetarian", "Healthy", "Gluten Free"],
    dishTypes: ["dinner", "soup", "healthy"],
    spoonacularScore: 95,
    nutrition: { calories: 310, protein: "14g", carbs: "56g", fat: "4g" }
  },
  {
    id: 209,
    title: "Lean Turkey & Crisp Romaine Lettuce Wrap Boats",
    image: "https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&w=800&q=80",
    readyInMinutes: 20,
    servings: 3,
    summary: "Lean ground turkey sautéed with water chestnuts, ginger, garlic, and hoisin sauce, served in crisp chilled romaine lettuce cups.",
    instructions: "1. Brown lean ground turkey in a wok with sesame oil.\n2. Add minced water chestnuts, garlic, ginger, soy sauce, and hoisin.\n3. Spoon warm turkey mixture into crisp cold romaine lettuce boats and top with scallions.",
    ingredients: ["1 lb Lean Ground Turkey (93/7)", "1 can Water Chestnuts, diced", "1 Head Romaine Lettuce", "2 tbsp Hoisin & Soy Sauce", "Ginger, Garlic & Scallions"],
    cuisines: ["Asian", "Healthy"],
    diets: ["Healthy", "High Protein", "Low Carb", "Keto"],
    dishTypes: ["lunch", "healthy"],
    spoonacularScore: 94,
    nutrition: { calories: 270, protein: "32g", carbs: "12g", fat: "10g" }
  },
  {
    id: 210,
    title: "Rainbow Summer Spring Rolls with Peanut Dip",
    image: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=800&q=80",
    readyInMinutes: 25,
    servings: 4,
    summary: "Delicate translucent rice paper rolls packed with crunchy purple cabbage, carrots, avocado, cucumber, mint, and served with spicy peanut sauce.",
    instructions: "1. Dip rice paper sheet in warm water for 5 seconds.\n2. Lay flat and place mint leaves, shredded cabbage, carrots, cucumber, and avocado.\n3. Roll tightly like a burrito.\n4. Whisk peanut butter, warm water, soy sauce, lime juice, and chili for dipping sauce.",
    ingredients: ["8 Rice Paper Sheets", "1 cup Shredded Purple Cabbage", "2 Carrots, julienned", "1 Avocado", "Fresh Mint & Cilantro", "1/3 cup Peanut Butter Sauce"],
    cuisines: ["Vietnamese", "Healthy"],
    diets: ["Vegan", "Vegetarian", "Healthy", "Gluten Free"],
    dishTypes: ["lunch", "healthy"],
    spoonacularScore: 95,
    nutrition: { calories: 230, protein: "7g", carbs: "30g", fat: "11g" }
  }
]
